version: '3.8'

services:
  neo4j:
    image: neo4j:5

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - ./src/ontology:/var/lib/neo4j/import

    environment:
      - NEO4J_PLUGINS=["apoc","n10s"]
      - NEO4J_dbms_security_procedures_unrestricted=n10s.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=n10s.*,apoc.*
      - NEO4J_AUTH=neo4j/password123