name: Auto Translate Issues

on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

permissions:
  contents: read
  issues: write

jobs:
  translate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: dromara/issues-translate-action@v2.7
        with:
          BOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_LOGIN_NAME: github-actions[bot]
          IS_MODIFY_TITLE: "false"
