name: Auto Translate Issues & Comments

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  translate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Translate Issue & Comment
        uses: dromara/issues-translate-action@v2.7
        with:
          BOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOT_LOGIN_NAME: github-actions[bot]
          IS_MODIFY_TITLE: "false"
          CUSTOM_BOT_NOTE: |
            🤖 Auto translated by GitHub Actions
